GET http://cal.syoboi.jp/json.php?Req=
###

GET http://cal.syoboi.jp/db.php?Command=ProgLookup&Range=20210110_000000-20210111_000000

###
GET http://cal.syoboi.jp/db.php?Command=ChLookup

###
GET http://cal.syoboi.jp/db.php?Command=TitleLookup&TID=3163

###
GET http://cal.syoboi.jp/db.php?Command=ProgLookup&JOIN=SubTitles&Range=20210215_000000-20210222_000000
